graph TD
    A[App Layout] --> B[Shop Layout]
    A --> C[Admin Layout]
    
    B --> D[Main Page]
    B --> E[Auth Page]
    B --> F[Register Page]
    B --> G[Profile Page]
    B --> H[Cart Page]
    B --> I[Orders Page]
    B --> J[Favorites Page]
    B --> K[Products Page]
    K --> L[Product Details Page]
    
    C --> M[Admin Main Page]
    C --> N[Admin Orders Page]
    C --> O[Admin Profiles Page]

    style A fill:#f9f,stroke:#333,stroke-width:2px
    style B fill:#bbf,stroke:#333,stroke-width:2px
    style C fill:#bbf,stroke:#333,stroke-width:2px
    style D fill:#dfd,stroke:#333,stroke-width:2px
    style E fill:#dfd,stroke:#333,stroke-width:2px
    style F fill:#dfd,stroke:#333,stroke-width:2px
    style G fill:#dfd,stroke:#333,stroke-width:2px
    style H fill:#dfd,stroke:#333,stroke-width:2px
    style I fill:#dfd,stroke:#333,stroke-width:2px
    style J fill:#dfd,stroke:#333,stroke-width:2px
    style K fill:#dfd,stroke:#333,stroke-width:2px
    style L fill:#dfd,stroke:#333,stroke-width:2px
    style M fill:#fdd,stroke:#333,stroke-width:2px
    style N fill:#fdd,stroke:#333,stroke-width:2px
    style O fill:#fdd,stroke:#333,stroke-width:2px 